INSERT OR REPLACE INTO guild_quests (id, guild_code, title, description, requirement_json, reward_json, resets_at, is_active, created_at) VALUES
  ('gquest-merchant-1', 'MERCHANT', 'Supply the Bazaar', 'Deliver 1,200 WOOD to stock the royal bazaar.',
   json_object('resource','WOOD','amount',1200),
   json_object('coins',1800,'favor',5,'guildReputation',8),
   NULL, 1, strftime('%s','now')*1000),
  ('gquest-merchant-2', 'MERCHANT', 'Luxury Shipment', 'Send 400 FABRIC to craft noble garments.',
   json_object('resource','FABRIC','amount',400),
   json_object('coins',2500,'crowns',5,'favor',6),
   NULL, 1, strftime('%s','now')*1000),
  ('gquest-gatherer-1', 'GATHERER', 'Stone Drive', 'Deliver 1,000 STONE for capital repairs.',
   json_object('resource','STONE','amount',1000),
   json_object('coins',1500,'favor',5,'boost',json_object('code','build_speed','hours',3)),
   NULL, 1, strftime('%s','now')*1000),
  ('gquest-gatherer-2', 'GATHERER', 'Fiber Relief', 'Send 800 FIBER to the royal tailors.',
   json_object('resource','FIBER','amount',800),
   json_object('coins',1400,'favor',4,'resources',json_object('FABRIC',120)),
   NULL, 1, strftime('%s','now')*1000),
  ('gquest-adventurer-1', 'ADVENTURER', 'Arms for the Vanguard', 'Donate 500 TOOLS to arm the vanguard.',
   json_object('resource','TOOLS','amount',500),
   json_object('coins',2200,'favor',7,'boost',json_object('code','army_morale','hours',6)),
   NULL, 1, strftime('%s','now')*1000),
  ('gquest-adventurer-2', 'ADVENTURER', 'Siege Support', 'Provide 300 INGOTS for siege engines.',
   json_object('resource','INGOTS','amount',300),
   json_object('coins',2600,'favor',8,'crowns',5),
   NULL, 1, strftime('%s','now')*1000);

